- name: for test run
  gather_facts: true
  hosts: all

  tasks:
    - name: Helo Word!
      shell: echo "Hello, it working"
      register: shell_result

    - ansible.builtin.debug:
      var: shell_result
