- name: for test run
  gather_facts: true
  hosts: all

  tasks:
    - name: Helo Word!
      shell: echo "Hello, it working"
      register: shellOutput
    - debug:
      msg: System {{ shellOutput }}
