- name: for test run
  gather_facts: true
  hosts: all

  tasks:
    - name: Helo Word!
      shell: |
        echo "Hello, it working"
        hostname
      register: shell_result
    
    - debug:
        var: shell_result
